name: Node Javascript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run eslint
        run: pnpm lint

      - name: Run prettier
        run: pnpm format:check
